apiVersion: v1
kind: Secret
metadata:
  name: webserver-ssl-secrets
type: Opaque
stringData:
  server-crt.pem: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  server-key.pem: |
    -----BEGIN PRIVATE KEY-----

    -----END PRIVATE KEY-----
