additionalArguments:
  # DNS Challenge with Cloudflare Example:
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=ahsanjsdev@gmail.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json

logs:
  # Configure log settings here...
  general:
    level: ERROR

ports:
  # Configure your entrypoints here...
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
      certResolver: cloudflare

env:
  # DNS Challenge Credentials (Cloudflare):
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cf-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cf-credentials

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command:
        [
          "sh",
          "-c",
          "touch  /ssl-certs/acme-cloudflare.json; chmod -v 600 /ssl-certs/acme-cloudflare.json",
        ]
      volumeMounts:
        - mountPath: /ssl-certs
          name: ssl-certs

# Security configurations for the deployment
podSecurityContext:
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Traefik as default Ingress Controller (for Kubernetes 1.19+)
ingressClass:
  enabled: true
  isDefaultClass: true
