apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx1
  namespace: default
spec:
  secretName: nginx1
  issuerRef:
    # name: acme-issuer
    name: cloudflare-clusterissuer
    kind: ClusterIssuer

  dnsNames:
    - "ahsanjsdev.tech"
    
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx1
  namespace: default
spec:
  secretName: nginx1
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - "ahsanjsdev.tech"
