# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: acme-issuer
# spec:
#   acme:
#     email: ahsanjsdev@gmail.com # Replace with your email address
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: cloudflare-api-key-secret
#     solvers:
#       - dns01:
#           cloudflare:
#             email: ahsanjsdev@gmail.com # Cloudflare account email
#             apiKeySecretRef:
#               name: cloudflare-api-key-secret
#               key: apiKey # Ensure the secret contains this key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    email: ahsanjsdev@gmail.com # <-- Replace with your email address
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
